const KEY='treino-leve-v1';
const seed={workouts:[{id:'A',name:'Costas / Bíceps',exercises:[
{name:'Remada baixa aberta',sets:3,note:'Travar escápula',history:[]},
{name:'Remada triângulo',sets:3,note:'Tronco não pode inclinar para trás',history:[]},
{name:'Puxada frente aberta',sets:3,note:'Puxar a barra sentado',history:[]},
{name:'Pulldown corda',sets:3,note:'Controle o movimento',history:[]},
{name:'Rosca martelo',sets:3,note:'Subir halteres na vertical',history:[]}
]}]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed; let route={p:'home'};
function save(){localStorage.setItem(KEY,JSON.stringify(db))} function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function last(w){let dates=w.exercises.flatMap(e=>e.history||[]).map(x=>x.ts||0); return dates.length?new Date(Math.max(...dates)).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}):'Ainda não feito'}
function render(){const a=document.getElementById('app'); if(route.p==='home')home(a); if(route.p==='workout')workout(a); if(route.p==='exercise')exercise(a); if(route.p==='session')session(a)}
function top(title,sub,back=true){return `<div class="top"> <div class="row">${back?`<button class="back" onclick="go('home')">‹</button>`:''}<div><div class="title">${esc(title)}</div>${sub?`<div class="sub">${esc(sub)}</div>`:''}</div></div></div>`}
function home(a){a.innerHTML=`<div class="top"><div><div class="title">Treino Leve</div><div class="sub">Seu treino, sem enrolação.</div></div><button class="primary" onclick="newWorkout()">+ Treino</button></div><div class="grid">${db.workouts.map(w=>`<div class="workout" onclick="openWorkout('${w.id}')"><div><h2>Treino ${esc(w.id)}</h2><div class="muted">${esc(w.name)}</div><span class="pill">${last(w)}</span></div><div class="arrow">›</div></div>`).join('')}</div><div class="section muted">Tudo fica salvo neste aparelho, inclusive offline.</div>`}
function workout(a){let w=db.workouts.find(x=>x.id===route.id);a.innerHTML=top(`Treino ${w.id}`,w.name)+`<div class="actions"><button class="primary" onclick="startSession()">▶ Iniciar treino</button><button class="secondary" onclick="newExercise()">+ Exercício</button><button class="secondary" onclick="renameWorkout()">Editar nome</button></div><div class="section"><div class="sectiontitle">Exercícios</div><div class="grid">${w.exercises.map((e,i)=>`<div class="exercise" onclick="openExercise(${i})"><h3>${esc(e.name)}</h3><small>${e.sets} séries${e.note?' · '+esc(e.note):''}</small><div class="muted" style="margin-top:8px">${e.history?.length?`Último: ${esc(e.history[0].summary)}`:'Sem histórico'}</div></div>`).join('')}</div></div>`}
function exercise(a){let w=db.workouts.find(x=>x.id===route.id),e=w.exercises[route.i];let h=e.history||[];a.innerHTML=top(e.name,`Treino ${w.id}`,false)+`<button class="secondary" onclick="openWorkout('${w.id}')">‹ Voltar ao treino</button><div class="section"><div class="sectiontitle">Observação</div><div class="history">${esc(e.note||'Nenhuma')}</div></div><div class="section"><div class="sectiontitle">Histórico</div>${h.length?h.slice(0,30).map(x=>`<div class="history"><b>${new Date(x.ts).toLocaleString('pt-BR')}</b><div class="muted">${esc(x.summary)}</div></div>`).join(''):'<div class="empty">Ainda não há registros para este exercício.</div>'}</div><button class="fab" onclick="quickSet()">+ Registrar série</button>`}
function session(a){let w=db.workouts.find(x=>x.id===route.id);a.innerHTML=top(`Treino ${w.id}`,`Registro de hoje`,false)+`<div class="muted">Registre as séries. O último treino fica disponível no histórico.</div><div class="section grid">${w.exercises.map((e,i)=>`<div class="exercise"><h3>${esc(e.name)}</h3><div class="muted">${e.sets} séries${e.history?.length?` · último: ${esc(e.history[0].summary)}`:''}</div><div class="series">${Array.from({length:e.sets},(_,j)=>`<div class="set" onclick="register(${i},${j})"><b id="s-${i}-${j}">＋</b><span>Série ${j+1}</span></div>`).join('')}</div></div>`).join('')}</div><button class="fab" onclick="finishSession()">Salvar treino</button>`}
function modal(title,fields,onSave){document.getElementById('modal').innerHTML=`<div class="sheet"><h2>${esc(title)}</h2>${fields.map((f,i)=>`<div class="field"><label>${esc(f.label)}</label><input id="f${i}" value="${esc(f.value||'')}" placeholder="${esc(f.placeholder||'')}"></div>`).join('')}<div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancelar</button><button class="primary" onclick="(${onSave.toString()})()">Salvar</button></div></div>`;document.getElementById('modal').classList.remove('hidden');}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function newWorkout(){modal('Novo treino',[{label:'Código',value:'B'},{label:'Nome',value:'Peito / Tríceps'}],()=>{let id=document.getElementById('f0').value.trim().toUpperCase(),name=document.getElementById('f1').value.trim();if(!id||!name)return;db.workouts.push({id,name,exercises:[]});save();closeModal();render()})}
function renameWorkout(){let w=db.workouts.find(x=>x.id===route.id);modal('Editar treino',[{label:'Nome',value:w.name}],()=>{w.name=document.getElementById('f0').value.trim()||w.name;save();closeModal();render()})}
function newExercise(){let w=db.workouts.find(x=>x.id===route.id);modal('Novo exercício',[{label:'Nome',placeholder:'Ex.: Supino reto'},{label:'Séries',value:'3'},{label:'Observação',placeholder:'Opcional'}],()=>{let n=document.getElementById('f0').value.trim();if(!n)return;w.exercises.push({name:n,sets:Math.max(1,+document.getElementById('f1').value||3),note:document.getElementById('f2').value.trim(),history:[]});save();closeModal();render()})}
function quickSet(){let w=db.workouts.find(x=>x.id===route.id),e=w.exercises[route.i];modal('Registrar série',[{label:'Carga (kg)',placeholder:'Ex.: 41'},{label:'Repetições',placeholder:'Ex.: 8'}],()=>{let kg=document.getElementById('f0').value.trim(),r=document.getElementById('f1').value.trim();if(!kg||!r)return;e.history.unshift({ts:Date.now(),summary:`${kg} kg × ${r} reps`});save();closeModal();toast('Série registrada');render()})}
function register(i,j){let w=db.workouts.find(x=>x.id===route.id),e=w.exercises[i];modal(`Série ${j+1} · ${e.name}`,[{label:'Carga (kg)'},{label:'Repetições'}],()=>{let kg=document.getElementById('f0').value.trim(),r=document.getElementById('f1').value.trim();if(!kg||!r)return;document.getElementById(`s-${i}-${j}`).textContent=`${kg}×${r}`;let key=`session-${route.id}-${i}`;window[key]=window[key]||[];window[key][j]=`${kg} kg × ${r} reps`;closeModal()})}
function startSession(){route.p='session';render()} function finishSession(){let w=db.workouts.find(x=>x.id===route.id),now=Date.now();w.exercises.forEach((e,i)=>{let key=`session-${route.id}-${i}`,sets=window[key]||[];if(sets.length)e.history.unshift({ts:now,summary:sets.filter(Boolean).join(' · ')})});save();toast('Treino salvo');route.p='workout';render()}
function openWorkout(id){route={p:'workout',id};render()} function openExercise(i){route.p='exercise';route.i=i;render()} function go(p){route={p};render()} function toast(t){let x=document.getElementById('toast');x.textContent=t;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),1600)}
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js'); render();
